name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r dist gs://${{ secrets.GCP_BUCKET_NAME }}
          gsutil iam ch allUsers:objectViewer gs://${{ secrets.GCP_BUCKET_NAME }}
          gsutil web set -m index.html -e index.html gs://${{ secrets.GCP_BUCKET_NAME }}